<?php

/**
 * @file
 * Primary module hooks for nostrides module.
 */

/**
 * Implements hook_theme().
 *
 * Register a module or theme's theme implementations.
 * The implementations declared by this hook specify how a
 * particular render array is to be rendered as HTML.
 *
 * See: https://api.drupal.org/api/drupal/core%21lib%21Drupal%21Core%21Render%21theme.api.php/function/hook_theme
 *
 * If you change this method, clear theme registry and routing
 * table 'drush cc theme-registry' and 'drush cc router'.
 */
function nostrides_theme($existing, $type, $theme, $path) {
  return [
    'nostrides-list' => [
      'render element' => 'children',
      'template' => 'nostrides',
      'path' => $path . '/templates',
      'variables' => [
        'events' => [],
      ],
    ],
    'nostrides-item' => [
      'render element' => 'children',
      'template' => 'nostrides-item',
      'path' => $path . '/templates',
      'variables' => [
        'event' => [],
      ],
    ]
  ];
}
