# Access via "http://localhost"
# (or "http://$(docker-machine ip):8080" if using docker-machine)

services:

  nostrverse_drupal:
    image: sebastix/drupal:11-php83-apache-amd64
    hostname: nostrverse_drupal
    container_name: nostrverse_drupal
    ports:
      - 80:80
      - 443:443
    volumes:
      - ../:/var/www:cached
      - ../config:/var/www/config:consistent
      - ./php/custom.ini:/usr/local/etc/php/conf.d/custom.ini
      - ./drupal/settings.local.php:/var/www/web/sites/default/settings.local.php
      - ./drupal/nyves-nl-settings.local.php:/var/www/web/sites/nyves.nl/settings.local.php
      - ./drupal/nostrides-cc-settings.local.php:/var/www/web/sites/nostrides.cc/settings.local.php
      - ./drupal/development.services.yml:/var/www/web/sites/development.services.yml
      - ./ssh/config:/root/.ssh/config
    environment:
      APACHE_DOCUMENT_ROOT: /var/www/web
      XDEBUG_SESSION: PHPSTORM
      PHP_IDE_CONFIG: "serverName=localhost"
      DRUSH_ALLOW_XDEBUG: 1
    extra_hosts:
      - host.docker.internal:host-gateway
    working_dir: /var/www
    secrets:
      - tinypc_ssh_key

  nostrverse_db:
    image: mariadb:10.11
    hostname: nostrverse_db
    container_name: nostrverse_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nostrverse_drupal
    ports:
      - 32768:3306

#  nlnostrverse_db:
#    image: mariadb:10.11
#    hostname: nlnostrverse_db
#    container_name: nlnostrverse_db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: nlnostrverse_drupal
#    ports:
#      - 32769:3306

#  nostrides_db:
#    image: mariadb:10.11
#    hostname: nostrides_db
#    container_name: nostrides_db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: nostrides_drupal
#    ports:
#      - 32770:3306

#  nyves_db:
#    image: mariadb:10.11
#    hostname: nyves_db
#    container_name: nyves_db
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: nyves_drupal
#    ports:
#      - 32771:3306

  # Access via http://localhost:8025/
  mailpit:
    image: axllent/mailpit
    hostname: mailpit
    ports:
      - 1025:1025
      - 8025:8025

secrets:
  tinypc_ssh_key:
    file: ~/.ssh/id_ed25519_tinypc
