<?php

/**
 * @file
 * Primary module hooks for njump module.
 */

function njump_theme($existing, $type, $theme, $path) {
  return [
    'njump' => [
      'render element' => 'children',
      'template' => 'njump',
      'path' => $path . '/templates',
      'variables' => [
        'identifier' => NULL,
        'event' => NULL,
        'author' => NULL,
        'nostr_event_node' => NULL,
      ],
    ]
  ];
}
