<?php

use Drupal\Core\Link;
use Drupal\Core\Url;
use Drupal\paragraphs\Entity\Paragraph;
use swentel\nostr\Event\Event;
use swentel\nostr\Event\Profile\Profile;
use swentel\nostr\Nip19\Nip19Helper;

/**
 * @file
 * Primary module hooks for njump module.
 */

function njump_preprocess_page_title(&$variables): void {
  // Get node
  $node = \Drupal::request()->attributes->get('node');
  if (!is_null($node) && $node->bundle() === 'nostr_event') {
    if ($node->hasField('field_nostr_kind')) {
      // Get field_nostr_kind
      $field_nostr_kind = $node->get('field_nostr_kind')->getString();
      // What Nostr event kinds have a required title?
      if ($field_nostr_kind !== '30023') {
        unset($variables['title']);
      }
    }
  }
}

/**
 * Alter nostr_event preprocess node page.
 *
 * @param $variables
 *
 * @return void
 * @throws \Exception
 */
function njump_preprocess_node__nostr_event(&$variables): void {
  $node = $variables['node'];
  $pubkey_author = $node->get('field_nostr_pubkey')->getString();
  try {
    $profile = new Profile();
    $profile->fetch($pubkey_author);
  }
  catch (\Exception $e) {
    throw new \RuntimeException($e->getMessage());
  }
  $nip19 = new Nip19Helper();
  $variables['npub'] = $nip19->encodeNpub($pubkey_author);
  $variables['nprofile'] = $nip19->encodeProfile($profile);
  $variables['profile'] = $profile;
  // Used in njump_page_attachments_alter.
  $tempstore = \Drupal::service('tempstore.private')->get('njump');
  $tempstore->set('author', $profile->name ?? $profile->display_name);
}

/**
 * Implements hook_page_attachments_alter().
 */
function njump_page_attachments_alter(array &$attachments):void {
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node && $node->bundle() === 'nostr_event') {
    $tempstore = \Drupal::service('tempstore.private')->get('njump');
    $author = $tempstore->get('author');
    // Find and update the author meta tag
    foreach ($attachments['#attached']['html_head'] as &$head_element) {
      if (
        isset($head_element[0]['#attributes']['name']) &&
        $head_element[0]['#attributes']['name'] === 'author'
      ) {
        $head_element[0]['#attributes']['content'] = $author;
        break;
      }
      }
    // Clean up the temporary value
    $tempstore->delete('author');
  }
}

/**
 * Alter field_nostr_content used in content type Nostr event.
 *
 * @param $variables
 *
 * @return void
 * @throws \JsonException
 */
function njump_preprocess_field__field_nostr_content(&$variables): void {
  // Get the node object.
  $node = $variables['element']['#object'];
  $content = $node->get('field_nostr_content')->getString();
  $kind = $node->get('field_nostr_kind')->getString();
  $paragraph_tags = $node->get('field_nostr_tags')->getValue();
  $tags = [];
  foreach ($paragraph_tags as $ref) {
    /** @var Paragraph $tag */
    $paragraph_tag = Paragraph::load($ref['target_id']);
    $tags[$paragraph_tag->get('field_nostr_tag_name')->getString()] = [
      'value' => $paragraph_tag->get('field_nostr_tag_value')->getString(),
      'parameters' => explode(',', $paragraph_tag->get('field_nostr_tag_parameters')->getString()),
    ];
  }
  // Profile event
  if ($kind === '0' && json_validate($content)) {
    // TODO parse profile metadata here.
    $profile = new Profile();
    $profile->parseProfile($content);
    return;
  }
  // Quote event
  if ($kind === '6' && json_validate($content)) {
    // This string is a valid JSON string
    $json = json_decode($content, false);
    $event = new Event();
    $event->populate($json);
    $variables['quoted_event'] = $event;
  }
  // TODO reaction event
  if ($kind === '7') {
    // TODO fetch event where the reaction is made on.
  }
  // TODO if the event is a note and a reaction, fetch the parent event (root or reply)
  if ($kind === '1' && isset($tags['e'])) {
    $variables['reply_to'] = $tags['e']['value'];
    // This is a reply (note kind 1) to a root event
    if (isset($tags['e']['parameters'][1])) {
      $variables['reply_parent'] = $tags['e']['parameters'][1];
    }
    $variables['reply_to'] = $tags['e']['value'];
  }
  if ($kind === '1' && isset($tags['a'])) {
    // @TODO fetch event with d-tag identifier so we can use the event id as a variable
    $variables['reply_to'] = $tags['a']['value'];
  }
  // TODO, can we build a tread with the parent event (root) and all reactions?

  /**
   * Check which identifiers we can replace in the content string
   * See NIP-21 - https://nips.nostr.com/21
   * nostr:npub1
   * nostr:note1
   * nostr:nevent1
   * nostr:nprofile1
   * nostr:addr1
   */
  $prefix_identifiers = 'nostr:';
  $identifiers = [
    'npub1',
    'note1',
    'nevent1',
    'nprofile1',
    'naddr1'
  ];
  // The content to search in for the to be replaced identifiers.
  $context = $variables['items'][0]['content']['#context']['value'];
  foreach ($identifiers as $identifier) {
    $pattern = '/'. $prefix_identifiers . $identifier .'\w+/m';
    if (preg_match_all($pattern, $context, $matches)) {
      $context = _replaceNostrIdentifiers($context, $matches[0]);
    }
  }

  /**
   * Replace links to media with elements to embed this content
   */
  $image_extensions = [
    'jpg',
    'jpeg',
    'png',
    'gif',
    'webp'
  ];
  foreach ($image_extensions as $extension) {
    $pattern = '/https?:\/\/.*\.(?:' . $extension . ')/m';
    if (preg_match_all($pattern, $context, $matches)) {
      $context = _replaceImageLinks($context, $matches[0]);
    }
  }

  /**
   * TODO replace hashtags with HTML link elements
   */

  /**
   * Replace links with video's
   */
  $video_extensions = ['mp4'];
  foreach ($video_extensions as $extension) {
    $pattern = '/https?:\/\/.*\.(?:' . $extension . ')/m';
    if (preg_match_all($pattern, $context, $matches)) {
      $context = _replaceVideoLinks($context, $matches[0]);
    }
  }

  /**
   * Replace external links to HTML link elements
   */
  $replace_links_pattern = '/(?<!src="|href="|alt=")(?<!src=\')(?<!href=\')(?<!alt=\')\bhttp(s)?:\/\/([\w-]+\.)+[\w-]+(\/[\w\- .\/?%&=]*)?(?!["\'][^<]*>|\s*["\'][^<]*>)/';
  $context = preg_replace($replace_links_pattern, '<a href="$0">$0</a>', $context);

  /**
   * Render Markup formatted content to HTML (kind 30023 and 30024)
   */

  $variables['items'][0]['content']['#context']['value'] =  $context;
}

/**
 * @param string $context
 * @param array $matches
 *
 * @return string
 */
function _replaceNostrIdentifiers(string $context, array $matches): string {
  foreach ($matches as $match) {
    [$uri, $identifier] = explode(':', $match, 2);
    $match_patterns = ['/' . $match . '/'];
    $url = new Url('njump.event', ['identifier' => $identifier]);
    $link = new Link($uri.':'.$identifier, $url);
    $replacements = [$link->toString()->getGeneratedLink()];
    // replace in context
    $context = preg_replace($match_patterns, $replacements, $context);
  }
  return $context;
}

/**
 * @param string $context
 * @param array $matches
 *
 * @return string
 */
function _replaceImageLinks(string $context, array $matches): string {
  foreach ($matches as $match) {
    $url = Url::fromUri($match);
    $link = new Link($match, $url);
    // TODO download and save image as a file (compressed) entity
    $image = sprintf('<img src="%s" alt="%s" />', $link->getUrl()->toString(), $link->getUrl()->toString());
    $match_patterns = ['/' . str_replace('/', '\/', $match) . '/'];
    $replacements = [$image];
    $context = preg_replace($match_patterns, $replacements, $context);
  }
  return $context;
}

/**
 * @param string $context
 * @param array $matches
 *
 * @return string
 */
function _replaceVideoLinks(string $context, array $matches): string {
  foreach ($matches as $match) {
    $url = Url::fromUri($match);
    $link = new Link($match, $url);
    $video = sprintf('<video controls="" playsinline="" class="rounded-lg max-h-[80vh] sm:max-h-[60vh] border mt-2" src="%s"></video>', $link->getUrl()->toString());
    $match_patterns = ['/' . str_replace('/', '\/', $match) . '/'];
    $replacements = [$video];
    $context = preg_replace($match_patterns, $replacements, $context) ?? '';
  }
  return $context;
}
